docked = false
terminal = false

packages = ['reactivex']

[[fetch]]
files = [
    '__init__.py',
    'app.py',
    'base/__init__.py',
    'base/component.py',
    'components/__init__.py',
    'components/footer.py',
    'components/header.py',
    'components/theme.py',
    'components/description_test.py',
    'services/__init__.py',
    'services/theme.py',
    'services/description_model.py',
]
from = 'calm_calatheas'
to_folder = 'calm_calatheas'
