docked = false
terminal = false

packages = ['pydantic', 'reactivex']

[[fetch]]
files = [
    '__init__.py',
    'app.py',
    'base/__init__.py',
    'base/component.py',
    'components/__init__.py',
    'components/camera.py',
    'components/footer.py',
    'components/header.py',
    'components/loading_caption_model.py',
    'components/theme.py',
    'components/description.py',
    'services/__init__.py',
    'services/camera.py',
    'services/caption.py',
    'services/reader.py',
    'services/theme.py',
    'services/description.py',
]
from = 'calm_calatheas'
to_folder = 'calm_calatheas'
