name: Lint

on:
    push:
        branches:
            - main
    pull_request:

concurrency: lint-${{ github.sha }}

jobs:
    lint:
        runs-on: ubuntu-latest

        env:
            PYTHON_VERSION: "3.13"

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python ${{ env.PYTHON_VERSION }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ env.PYTHON_VERSION }}

            - name: Install uv
              run: python -m pip install uv

            - name: Cache the virtualenv
              uses: actions/cache@v4
              with:
                  path: ./.venv
                  key: ${{ runner.os }}-venv-${{ hashFiles('**/uv.lock') }}

            - name: Install Python dependencies
              run: uv venv --allow-existing && uv sync

            - name: Update GITHUB_PATH
              run: echo "$(uv python find)" >> $GITHUB_PATH

            - name: Setup Node.js and dependencies
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm
                  registry-url: "https://npm.pkg.github.com"

            - name: Install Node.js dependencies
              run: npm install
              shell: bash

            - name: Run pre-commit hooks
              uses: pre-commit/action@v3.0.1

            - name: Run the tests
              run: uv run pytest tests

            - name: Build the documentation
              run: uv run mkdocs build --strict
